{{- if .Values.imsApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "essp.fullname" . }}-ims-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "essp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ims-api
spec:
  type: {{ .Values.imsApi.service.type }}
  ports:
  - port: {{ .Values.imsApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "essp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ims-api
{{- end }}
