apiVersion: v1
kind: Service
metadata:
  name: ssot-school
  namespace: essp
  labels:
    app: ssot-school
    app.kubernetes.io/name: ssot-school
    app.kubernetes.io/component: ssot
    app.kubernetes.io/part-of: essp-platform
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ssot-school
  sessionAffinity: None
