apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ssot-school-pdb
  namespace: essp
  labels:
    app: ssot-school
    app.kubernetes.io/name: ssot-school
    app.kubernetes.io/component: ssot
    app.kubernetes.io/part-of: essp-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ssot-school
