apiVersion: v2
name: essp
description: EdVirons School Services Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - essp
  - school-services
  - microservices
maintainers:
  - name: EdVirons Team
    email: dev@edvirons.com
